### ISSUE TITLE
Add LR_GapCloser

### ISSUE THREAD

**Issue by macmanes** [shaniAmare/long_read_tools#33]
https://academic.oup.com/gigascience/article/8/1/giy157/5256637

**Comment by shaniAmare** [comment]
Thanks. We have added this to the local copy of the database. Will be updated with the next commit.  However, the link to the source code of LR_Gapcloser is not currently working.

**Comment by shaniAmare** [comment]
Thank you again - the tool is now accessible through the database! We really appreciate your contribution.
