### ISSUE TITLE
pycoQC link

### ISSUE THREAD

**Issue by Nazeeefa** [shaniAmare/long_read_tools#34]
Hi,

Just a tiny point, the link to pycoQC mentioned on the website doesn't work (it's missing hyphen). The correct link is https://github.com/a-slide/pycoQC

Cheers,
Nazeefa

**Comment by shaniAmare** [comment]
Corrected in the local copy. Will be pushed in the next update. Thanks for noticing.

**Comment by shaniAmare** [comment]
The link has been corrected on the new update. Thanks. We really appreciate your contribution in making the database as accurate as possible.
