### ISSUE TITLE
Webpage doesn't work

### ISSUE THREAD

**Issue by biozhangzhou** [shaniAmare/long_read_tools#36]
Hello
I have visited the old version webpage of Long-reads-tools several times, but now I cann't loading any tools in the new verison webpage.
Anything wrong about it ?
Thanks.

**Comment by shaniAmare** [comment]
Hi,

I think this not an issue anymore, so will close it. Feel free to open it if you have further queries.

Cheers,
Shani.

**Comment by biozhangzhou** [comment]
thanks
