### ISSUE TITLE
TRiCoLOR

### ISSUE THREAD

**Issue by Nazeeefa** [shaniAmare/long_read_tools#45]
Tandem Repeats Caller for LOng Reads https://github.com/davidebolo1993/TRiCoLOR

**Comment by shaniAmare** [comment]
Hi @Nazeeefa,

Thanks for adding this tool - it will be available with the new update. Alternatively, you can use the [Submit page](https://long-read-tools.org/submit.html) from the database itself to provide more info on the tools you submit.

Cheers
Shani.
