### ISSUE TITLE
primer and adapter trimming group

### ISSUE THREAD

**Issue by pcantalupo** [shaniAmare/long_read_tools#51]
Hello,

Why isn't there a primer and adapter trimming group?  This would include software such as Porechop and [pychopper](https://github.com/nanoporetech/pychopper)

**Comment by shaniAmare** [comment]
Hi,

We have a category called `quality trimming` I think which would fit the broader category of what you are asking for. `Pychopper `and `Porechop `are also in the database but have not been categorised in this category. This will get updated in the next release.

Thanks for your interest!
Shani.
